### PR TITLE
fix(type assert): add more check for type assert

### LINKED ISSUE #224: Report unchecked type-assertion when returning value and when passing it to other func
Two false negatives here when using the `-asserts` flag:

```go
package main

func main() {
	var i interface{} = "hello"

	_ = handleInterface(i)

	handleString(i.(string)) // This should be reported but isn't
}

func handleInterface(i interface{}) string {
	return i.(string) // This should be reported but isn't
}

func handleString(s string) {}
```

### PR DESCRIPTION
**Pull request by meteorgan**
fix #224

### CODE REVIEW

File: errcheck/errcheck.go [hunk 1]
```diff
@@ -586,18 +586,29 @@ func (v *visitor) Visit(node ast.Node) ast.Visitor {
...
 
 	case *ast.AssignStmt:
-		v.checkAssignment(stmt.Lhs, stmt.Rhs)
+		followed := v.checkAssignment(stmt.Lhs, stmt.Rhs)
+		if !followed {
+			return nil
+		}
+
+	case *ast.TypeAssertExpr:
+		v.checkAssertExpr(stmt)
```
Comment (dtcaciuc) [inline errcheck/errcheck.go:602]: You made this method return a boolean but you're not using the return value.

**Review by dtcaciuc — CHANGES_REQUESTED** [review]

File: errcheck/errcheck.go [hunk 2]
```diff
@@ -586,18 +586,29 @@ func (v *visitor) Visit(node ast.Node) ast.Visitor {
...
+		return nil
 
 	default:
 	}
 	return v
 }
 
-func (v *visitor) checkAssignment(lhs, rhs []ast.Expr) {
+func (v *visitor) checkAssignment(lhs, rhs []ast.Expr) (followed bool) {
+	followed = true
```
Comment (dtcaciuc) [inline errcheck/errcheck.go:611]: You should probably convert everything here to explicit returns (seems like only line 616 and 619 left) so that there's one way to do things.

Please add a doscstring explaining what return value means here.

**Review by dtcaciuc — APPROVED** [review]
Thanks, just one more nit, otherwise LGTM

**Review by dtcaciuc — APPROVED** [review]
👍
